[versions]

jspecify = "0.3.0"
jetbrains_annotations = "24.1.0"
autoservice = "1.1.1"

managedversioning = "1.2.17"
nexuspublish = "1.3.0"
gradlepublish = "1.2.1"

gradle_foojay = "0.8.0"
gradle_develocity = "3.17.2"

spotless = "6.25.0"

[libraries]

jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }
jetbrains_annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains_annotations" }
autoservice = { module = "com.google.auto.service:auto-service", version.ref = "autoservice" }

gradle_foojay = { module = "org.gradle.toolchains.foojay-resolver-convention:org.gradle.toolchains.foojay-resolver-convention.gradle.plugin", version.ref = "gradle_foojay" }
gradle_develocity = { module = "com.gradle.develocity:com.gradle.develocity.gradle.plugin", version.ref = "gradle_develocity" }
spotless = { module = "com.diffplug.spotless:com.diffplug.spotless.gradle.plugin", version.ref = "spotless" }

[bundles]

compileonly = ["jspecify", "jetbrains_annotations", "autoservice"]
annotationprocessor = ["autoservice"]

[plugins]

managedversioning = { id = "dev.lukebemish.managedversioning", version.ref = "managedversioning" }
nexuspublish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexuspublish" }
gradlepublish = { id = "com.gradle.plugin-publish", version.ref = "gradlepublish" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
