[versions]

jspecify = "0.3.0"
jetbrains_annotations = "24.1.0"
autoservice = "1.1.1"

managedversioning = "1.2.6"
nexuspublish = "1.3.0"
gradlepublish = "1.1.0"

gradle_foojay = "0.8.0"
gradle_enterprise = "3.16.2"

[libraries]

jspecify = { module = "dev.jspecify:jspecify", version.ref = "jspecify" }
jetbrains_annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains_annotations" }
autoservice = { module = "com.google.auto.service:auto-service", version.ref = "autoservice" }

gradle_foojay = { module = "org.gradle.toolchains:foojay-resolver", version.ref = "gradle_foojay" }
gradle_enterprise = { module = "com.gradle:gradle-enterprise-gradle-plugin", version.ref = "gradle_enterprise" }

[bundles]

compileonly = ["jspecify", "jetbrains_annotations", "autoservice"]
annotationprocessor = ["autoservice"]

[plugins]

managedversioning = { id = "dev.lukebemish.managedversioning", version.ref = "managedversioning" }
nexuspublish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexuspublish" }
gradlepublish = { id = "com.gradle.plugin-publish", version.ref = "gradlepublish" }
